runtime: python310
entrypoint: gunicorn -b :$PORT paultolrem.wsgi:application
instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: 'paultolrem.settings'

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
